### ISSUE TITLE
Request: Split

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [kgar/foundry-vtt-more-handlebars-helpers#1]
Can you please add: 

**Split**
[{{split}}](https://github.com/helpers/handlebars-helpers/blob/master/lib/string.js#L547)
Split string by the given character.

**Params**
string {String}: The string to split.
returns {String} character: Default is an empty string.
Example

**Example** 
{{split "a,b,c" ","}}

**Helper**
```
helpers.split = function(str, ch) {
  if (!util.isString(str)) return '';
  if (!util.isString(ch)) ch = ',';
  return str.split(ch);
};
```

**Comment by kgar** [comment]
Can do!

The code sample in the issue has brought to mind that I need to make some decisions on how to handle when a non-string is provided to string-based helpers.

The sample code provides a fallback for the text and for the separator. 
- if the input is not a string, my intuition is to simply return the provided value untouched, rather than falling back to an empty string
- the standard JavaScript `String.prototype.split()` function does not default `separator` to `','` when `separator` is not provided. I'm more apt to mimic this behavior rather than provide a default.

Check out the resulting code and let me know if you have any thoughts on this.

**Comment by ObsidianTTRPGProject** [comment]
Thank you. This works perfectly!
